import { BarChart3, Grid3x3, Home, Plus, Settings } from "lucide-react";

export const categoryIconOptions = [
  "ShoppingCart",
  "Car",
  "Tv",
  "FileText",
  "Coffee",
  "ShoppingBag",
  "Heart",
  "Briefcase",
  "Code",
  "TrendingUp",
  "Home",
  "Plane",
  "Book",
  "Music",
  "Dumbbell",
  "Gift",
  "Phone",
  "Laptop",
];

export const iconCategoriesOptions = [
  "ShoppingCart",
  "UtensilsCrossed",
  "Car",
  "House",
  "Tv",
  "Smartphone",
  "Laptop",
  "Plane",
  "Bus",
  "Fuel",
  "HeartPulse",
  "Pill",
  "Dumbbell",
  "GraduationCap",
  "Book",
  "Briefcase",
  "BadgeDollarSign",
  "TrendingUp",
  "PiggyBank",
  "Wallet",
  "Gift",
  "PartyPopper",
  "Gamepad2",
  "Music",
  "Film",
  "Coffee",
  "Shirt",
  "ShoppingBag",
  "Scissors",
  "Wrench",
  "Lightbulb",
  "Wifi",
  "Droplets",
  "Shield",
  "FileText",
  "Coins",
  "Banknote",
  "Dog",
  "Cat",
  "Baby",
  "Users",
  "Church",
  "TreePine",
  "Palette",
  "Camera",
  "Code",
  "Globe",
  "Shapes",
  "MoreHorizontal",
];

export const iconPaymentMethodsOptions = [
  "Wallet",
  "CreditCard",
  "Building2",
  "Smartphone",
  "QrCode",
  "Bitcoin",
  "PiggyBank",
  "Coins",
  "Landmark",
  "Receipt",
];

export const colorOptions = [
  "#10b981",
  "#3b82f6",
  "#8b5cf6",
  "#ef4444",
  "#f59e0b",
  "#ec4899",
  "#06b6d4",
  "#84cc16",
  "#f97316",
  "#6366f1",
];

export const BREAKPOINTS = {
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
  "2xl": 1536,
};

 export const navItems = [
    { path: '/', icon: Home, label: 'Home' },
    { path: '/analytics', icon: BarChart3, label: 'Analytics' },
    { icon: Plus, label: 'Add', isButton: true },
    { path: '/manage', icon: Grid3x3, label: 'Manage' },
    { path: '/settings', icon: Settings, label: 'Settings' },
  ];